// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBh7yTihG8kAxZSoE_OcmPQcWrKV4VzI',
    appId: '1:16226125981:web:e39cc9078f8b5b8acbac74',
    messagingSenderId: '16226125981',
    projectId: 'dart-calculator-with-login',
    authDomain: 'dart-calculator-with-login.firebaseapp.com',
    storageBucket: 'dart-calculator-with-login.firebasestorage.app',
    measurementId: 'G-KWVJ0PLL0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1x46P_5g7Hv_7YkP_PBhuxEcFACLzcQ',
    appId: '1:16226125981:android:efb657ecb4fdd04ecbac74',
    messagingSenderId: '16226125981',
    projectId: 'dart-calculator-with-login',
    storageBucket: 'dart-calculator-with-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLjvi_aRTLWPxuWFc97ELkqQF9sgIciO4',
    appId: '1:16226125981:ios:766470b451d3151ecbac74',
    messagingSenderId: '16226125981',
    projectId: 'dart-calculator-with-login',
    storageBucket: 'dart-calculator-with-login.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLjvi_aRTLWPxuWFc97ELkqQF9sgIciO4',
    appId: '1:16226125981:ios:766470b451d3151ecbac74',
    messagingSenderId: '16226125981',
    projectId: 'dart-calculator-with-login',
    storageBucket: 'dart-calculator-with-login.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBh7yTihG8kAxZSoE_OcmPQcWrKV4VzI',
    appId: '1:16226125981:web:3913505fb79e0514cbac74',
    messagingSenderId: '16226125981',
    projectId: 'dart-calculator-with-login',
    authDomain: 'dart-calculator-with-login.firebaseapp.com',
    storageBucket: 'dart-calculator-with-login.firebasestorage.app',
    measurementId: 'G-V2T3NLW96M',
  );

}